# Site settings
title: Felip B Medeiros
description: 'Alguma breve descrição minha aqui, mas em breve.'
url: 'https://lip.sh/'
baseurl: ''
locale: pt_BR

author:
  name: 'Felip Barbosa'
  email: felip@member.fsf.org
  twitter_username: L1P
  github_username:  fel1p
  telegram_username: fel1p
  psn_username:  m-ked0n

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 3
excerpt_separator: <!--mais-->
permalink: /:categories/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'LICENSE', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
